### ISSUE TITLE
imgutil images should be v1.Images

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/imgutil#207]
Currently, a `layout.Image` implements the `v1.Image` interface (because the underlying "base" image is embedded). With some small changes, `remote.Image` could follow this pattern. `local.Image` is trickier because of the daemon, but with some work we could assemble enough information to return a `v1.ConfigFile`, erroring if a manifest is requested. We'll need to be careful to distinguish what is the "saved" image vs the "working image" (e.g., after `AddLayer` is called the layer is added to the working image but not the image that's saved in the disk/registry/daemon) but if we do it right we can remove a bunch of duplication across the layout/remote/local packages and make the interface more intuitive to work with.

**Comment by sagnik3788** [comment]
@natalieparellano may I give it a try? It would be helpful for me if you could share some insights about this issue. Thank you

**Comment by natalieparellano** [comment]
@sagnik3788 aye, I actually took this up before the winter break and it turned out to be VERY involved. I will probably put a PR up for it soon (I should probably have assigned myself the issue before) - when that is up I would appreciate any help in reviewing it, which would also be a great help :)
