### ISSUE TITLE
WindowsWriter needs to add `Files` prefix to links

### ISSUE THREAD

**Issue by micahyoung** [buildpacks/imgutil#50]
At present, any link added to a Windows layer entry gets `Files` prepended to the `header.Name` but not to the `header.Linkname` meaning the expanded file would be invalid.

This WindowsWriter should be changed to prepend `Files` to `header.Linkname` as well as `header.Name`.

Related implementation:
https://github.com/moby/buildkit/blob/56e2ea083a4a392da9fb3a25a9e7cae34430948e/util/winlayers/differ.go#L245-L247

**Comment by micahyoung** [comment]
After some experimenting, we found this is not fixable in `imgutil`. The only valid type of value for `header.LinkName` would be a relative path (ex `my-link => bin/detect`) and those already work without a `Files` prefix. 

Absolute paths also don't work for Linux tar.Writer (they're copied over completely and not rewritten by Docker on extraction) so likewise on Windows, a user would need to set the correct absolute path value for `header.Linkname`. 

Windows:
```
12/31/1979  05:00 PM    <DIR>          bin                                
12/31/1979  05:00 PM               162 buildpack.toml                     
12/31/1979  05:00 PM    <SYMLINK>      dirlink-absolute-bin [\Users\micah\workspace\pack\sandbox\hello-windows\bin]                       
12/31/1979  05:00 PM    <SYMLINK>      dirlink-absolute-buildpack.toml [\Users\micah\workspace\pack\sandbox\hello-windows\buildpack.toml] 
12/31/1979  05:00 PM    <SYMLINK>      dirlink-relative-bin [bin]                       
12/31/1979  05:00 PM    <SYMLINK>      dirlink-relative-buildpack.toml [buildpack.toml] 
12/31/1979  05:00 PM    <SYMLINK>      dirlink-relback-bin [..\hello-windows\bin]       
12/31/1979  05:00 PM    <SYMLINK>      dirlink-relback-buildpack.toml [..\hello-windows\buildpack.toml]
```
Linux:
```
drwxr-xr-x 2 root root 4096 Jan  1  1980 bin
-rwxr-xr-x 1 root root  162 Jan  1  1980 buildpack.toml
lrwxrwxrwx 1 root root   53 Jan  1  1980 dirlink-absolute-bin -> /Users/micah/workspace/pack/sandbox/hello-windows/bin
lrwxrwxrwx 1 root root   64 Jan  1  1980 dirlink-absolute-buildpack.toml -> /Users/micah/workspace/pack/sandbox/hello-windows/buildpack.toml
lrwxrwxrwx 1 root root    3 Jan  1  1980 dirlink-relative-bin -> bin
lrwxrwxrwx 1 root root   14 Jan  1  1980 dirlink-relative-buildpack.toml -> buildpack.toml
lrwxrwxrwx 1 root root   20 Jan  1  1980 dirlink-relback-bin -> ../hello-windows/bin
lrwxrwxrwx 1 root root   31 Jan  1  1980 dirlink-relback-buildpack.toml -> ../hello-windows/buildpack.toml
```

**Comment by ekcasey** [comment]
> Absolute paths also don't work for Linux tar.Writer (they're copied over completely and not rewritten by Docker on extraction) so likewise on Windows, a user would need to set the correct absolute path value for header.Linkname.

Can you elaborate on this part a little. If you explicitly set `header.Linkname` to an absolute path that will exist in the container, `docker` will not handle it correctly when creating the container?

**Comment by micahyoung** [comment]
Sorry for no reply. I'm afraid I lost the context on this and I feel like this has been sorted out with the slice-related `lifecycle` changes, so incoming symlinks are sure to have the correct value on both OSes
