### ISSUE TITLE
Revert docker version upgrade

### ISSUE THREAD

**Issue by jromero** [buildpacks/imgutil#70]
The recent update of the docker/docker lib #68 has created negative cascading effects in regards to how pack can import `lifecycle` + `imgutil` + `docker` libraries (plus other dependencies that update golang's `sys` package).

Prior to said PR, we were using **v1.4.2-0.20190924003213-a8608b5b67c7** (the same version as [GGCR](https://github.com/google/go-containerregistry/blob/master/go.mod#L15)).

At a high-level, most of the issues stem from that fact that docker/docker (aka [moby/moby](https://github.com/moby/moby) aka [docker/engine](https://github.com/docker/engine) 😓) is not `go module` friendly...

Relevant conversations:
- https://github.com/moby/moby/issues/41503
- https://github.com/moby/moby/issues/39302
- https://github.com/moby/moby/issues/39056

...making some lower level dependencies trail off and cause conflicts such as: 

- https://github.com/buildpacks/pack/pull/901#issuecomment-713558675
- https://github.com/buildpacks/pack/pull/895#issuecomment-713069370

Various attempts are resolving this issue have yield erratically unexpected failures (primarily affecting Windows).

Solutions attempted:
- Pinning to `sys` package of upgraded docker version: https://github.com/ory/dockertest/issues/208#issuecomment-686820414
- (Just 'cause) Pointing to docker/engine: https://github.com/moby/moby/issues/39302#issuecomment-504180486
- Pinning to docker/docker@master

I don't propose we indefinitely remain at the prior version but we should be more strategic in the upgrade based on our current dependency structure. I suspect that pack ran into this issue sooner rather than later but other platforms may find similar issues.

I would propose that we **test** and coordinate the upgrade in the following order `GGCR` -> `imgutil` -> `lifecycle` -> `pack`.

**Comment by ekcasey** [comment]
Yeah, this is a pain but I agree.
