### ISSUE TITLE
Add codecov support

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/imgutil#72]
As preparation for https://github.com/buildpacks/pack/issues/814, I was hoping to get the test coverage of code that I port over to this repo, to ensure that it's sufficiently tested to be a library component, but I noticed that codecov (or a similar code coverage tool) isn't used. 

If you could add, so I could have more reassurance that my code is sufficiently tested, and so users could have more confidence in the repo, that would be very helpful.

**Comment by satyazzz123** [comment]
@natalieparellano I have raised a PR to add codecov to imgutil for test coverage. Please have a look . Thank you
