### ISSUE TITLE
Images created against docker daemon failed to get saved against remote Artifactory

### ISSUE THREAD

**Issue by ashwin-venkatesh** [buildpacks/imgutil#9]
Images created using the local package seem to experience errors when the remote package is used to save the previously created image against a remote artifactory. (When performing a `remote.Write`)

The artifactory returns the error `MANIFEST_INVALID: manifest invalid;`

Preliminary investigations make it seem like the Config files created are different for either image (remote vs local). What was a little weird is that we were able to use the docker CLI to push the image to artifactory but were unable to use GGCR to perform the same operation.
Additionally, performing an operation like `mutate.CreatedAt` on the image updated the config to become a "valid" one.

Let me know if I can provide any further information.

**Comment by jromero** [comment]
What version (aka commit hash) are you using? Is there a pared down sample of code to reproduce this issue?

**Comment by ashwin-venkatesh** [comment]
Sorry. I just read this. I feel bad. This was behavior we witnessed with pack 0.2.1. 
We created a builder without the publish flag, used docker push to push the image on gcr.io. We then used this relocation library https://github.com/pivotal/image-relocation to relocate the image to an artifactory registry. 
We saw this relocation fail with the Invalid manifest error.

**Comment by ekcasey** [comment]
resolved by #20
